local get_mcm_config = autocomplete_tasks_mcm.get_config
local dbg_printf = autocomplete_tasks_utils.dbg_printf
local utils = autocomplete_tasks_utils

task_manager_task_callback = task_manager.task_callback
task_manager.task_callback = function(tsk, stage)
	-- Check if user wants to compensate items
	if not get_mcm_config("at_general", "enable") or not get_mcm_config("at_general", "compensate_item_rewards") then
		task_manager_task_callback(tsk, stage)
		return
	end

	local task_id = tsk and tsk:get_id()
    if not task_id then
        task_manager_task_callback(tsk, stage)
        return
    end

	-- Check if last stage
	if stage ~= task.completed then
		dbg_printf("[AT] No compensation for task %s: not completed yet", tsk_id)
		task_manager_task_callback(tsk, stage)
		return
	end

	-- Check if task id is cached
    local task_def = autocomplete_tasks_core.get_task_definition(task_id)
	if not task_def then
		dbg_printf("[AT] No compensation for task %s: task not cached", task_id)
		task_manager_task_callback(tsk, stage)
		return
	end

	-- Check if task should get autocompleted
	if not autocomplete_tasks_rules.should_autocomplete(task_id, task_def.stage_complete, task_def) then
		dbg_printf("[AT] No compensation for task %s: task category not enabled", task_id)
		task_manager_task_callback(tsk, stage)
		return
	end

	-- Get info about task
    local tm = task_manager.get_task_manager()
	local rtask = tm and tm.task_info and tm.task_info[task_id]
	if not rtask or not rtask.on_complete or not rtask.on_complete[1] or not rtask.on_complete[1][3] then
		printf("![AT] No compensation for task %s: on_complete attribute is non-existent or invalid", task_id)
		task_manager_task_callback(tsk, stage)
		return
	end

	-- Get task compensation prices
	local compensation = autocomplete_tasks_rewards.calculate_compensation(rtask.on_complete[1][3])
	if not compensation then
		printf("![AT] No compensation for task %s: no compensation prices found", task_id)
		task_manager_task_callback(tsk, stage)
		return
	end

	dbg_printf("[AT] Before edit of on complete table: \n%s", utils_data.print_table(rtask.on_complete[1][3], nil, true))

	-- Assign table copy to 'on_complete' rewards table for task
	dbg_printf("[AT] Used sell discount %s for compensation", utils.get_generic_sell_discount())
	dbg_printf("[AT] Total reward after item compensation with min reward %s and max reward %s", compensation.min, compensation.max)
	rtask.on_complete[1][3] = compensation.rewards

	dbg_printf("[AT] After edit of on complete table: \n%s", utils_data.print_table(rtask.on_complete[1][3], nil, true))

	task_manager_task_callback(tsk, stage)
end

sim_board_simulation_board_remove_squad = sim_board.simulation_board.remove_squad
sim_board.simulation_board.remove_squad = function(self, squad)
	-- Stop talking with squad before releasing the squad since it causes a CTD
	-- Needed for autocompletion of hostage tasks
	utils.stop_talk_squad(squad)

	sim_board_simulation_board_remove_squad(self, squad)
end
